import head from 'next/head'
import image from 'next/image'
import styles from '../styles/Home.module.css'


export default function firstWeb() {
    const [value, onChange] = useState(new Date());
  return (
    <div className={styles.container}>
    
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    
}
